language: java

before_install:
  - chmod +x gradlew

stages:
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: release
      script:
        - ./gradlew -Prelease.useLastTag=true final --info --stacktrace
